export const firebaseConfig = {
  apiKey: "AIzaSyASRUio4zXA36ZnmkNzPv4LRbD91hr7Sjs",
  authDomain: "tswpropertysolution.firebaseapp.com",
  databaseURL: "https://tswpropertysolution-default-rtdb.firebaseio.com",
  projectId: "tswpropertysolution",
  storageBucket: "tswpropertysolution.appspot.com",
  messagingSenderId: "1074626422597",
  appId: "1:1074626422597:web:ce1bdffc99c5bbea68c02c",
  measurementId: "G-BZMVE9Z4GG"
};

global.suburbsItems = [
{Name:'Select'},
{Name:'Aeroglen'},
{Name:'Aloomba'},
{Name:'Atherton'},
{Name:'Barron'},
{Name:'Bayview Heights'},
{Name:'Bentley Park'},
{Name:'Brinsmead'},
{Name:'Bungalow'},
{Name:'Cairns City'},
{Name:'Cairns North'},
{Name:'Caravonica'},
{Name:'Clifton Beach'},
{Name:'Earlville'},
{Name:'Edge Hill'},
{Name:'Edmonton'},
{Name:'Ellis Beach'},
{Name:'Freshwater'},
{Name:'Gordonvale'},
{Name:'Holloways Beach'},
{Name:'Kamerunga'},
{Name:'Kanimbla'},
{Name:'Kewarra Beach'},
{Name:'Kuranda'},
{Name:'Machans Beach'},
{Name:'Manoora'},
{Name:'Manunda'},
{Name:'Mareeba'},
{Name:'Mooroobool'},
{Name:'Mount Sheridan'},
{Name:'Palm Cove'},
{Name:'Parramatta Park'},
{Name:'Portsmith'},
{Name:'Redlynch'},
{Name:'Smithfield'},
{Name:'Stratford'},
{Name:'Trinity Beach'},
{Name:'Trinity Park'},
{Name:'Westcourt'},
{Name:'White Rock'},
{Name:'Whitfield'},
{Name:'Woree'},
{Name:'Yorkeys Knob'}
];


 